name: Generate Full TR Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # Her gün UTC 06:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Generate playlist
        run: python generate_playlist_auto.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Update full TR playlist (ulusal + freeshot)"
          git push