name: Update M3U Playlists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Haftada bir Pazar günü çalışır

jobs:
  generate-m3u:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install requests

    - name: Run M3U generator script
      run: python generate_m3u.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.m3u
        git diff --staged --quiet || git commit -m "Update M3U playlists"
        git push
